// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOTtnqAql1cp5YOY1Rz45lWlG12mbwaps',
    appId: '1:673388066360:web:fa1b6825589db7156858cd',
    messagingSenderId: '673388066360',
    projectId: 'form-sense',
    authDomain: 'form-sense.firebaseapp.com',
    storageBucket: 'form-sense.firebasestorage.app',
    measurementId: 'G-RJSWHCLL17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNDSNO51u796GCdh-CcmltZNTjfaGdHQ',
    appId: '1:673388066360:android:fac20701cd6a987b6858cd',
    messagingSenderId: '673388066360',
    projectId: 'form-sense',
    storageBucket: 'form-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjMMJg1TuXDOYEUQREGrs2I0kcsepxQg',
    appId: '1:673388066360:ios:78ca1365a501c5af6858cd',
    messagingSenderId: '673388066360',
    projectId: 'form-sense',
    storageBucket: 'form-sense.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFjMMJg1TuXDOYEUQREGrs2I0kcsepxQg',
    appId: '1:673388066360:ios:78ca1365a501c5af6858cd',
    messagingSenderId: '673388066360',
    projectId: 'form-sense',
    storageBucket: 'form-sense.firebasestorage.app',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOTtnqAql1cp5YOY1Rz45lWlG12mbwaps',
    appId: '1:673388066360:web:a8a1707d8edbd8196858cd',
    messagingSenderId: '673388066360',
    projectId: 'form-sense',
    authDomain: 'form-sense.firebaseapp.com',
    storageBucket: 'form-sense.firebasestorage.app',
    measurementId: 'G-ZG1XCQCHN8',
  );
}
